// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Use Prisma dev server URL or env variable
    url: process.env["DATABASE_URL"] || "postgres://postgres:postgres@localhost:51214/template1?sslmode=disable",
  },
});
