openapi: 3.0.3
info:
  title: GACP Platform - Pricing API
  version: 2.0.0
  description: |
    Pricing endpoints for GACP platform.
    Provides centralized pricing information for all platform fees.
    Part of "One Brain, Many Faces" architecture.
  contact:
    name: API Support
    email: support@gacp-botanical.com

servers:
  - url: http://localhost:3001
    description: Local development
  - url: https://api.gacp-botanical.com
    description: Production

tags:
  - name: Pricing
    description: Platform fee and pricing operations

paths:
  /api/v2/pricing/fees:
    get:
      tags:
        - Pricing
      summary: Get all platform fees
      description: Returns all pricing information for the platform
      operationId: getPlatformFees
      responses:
        '200':
          description: Fees retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FeesResponse'
              example:
                success: true
                data:
                  applicationFee: 5000
                  inspectionFee: 25000
                  renewalFee: 15000
                  expediteFee: 10000
                  currency: THB
                  vatRate: 0
                  lastUpdated: '2025-01-01'
                  validUntil: '2025-12-31'

  /api/v2/pricing/quotation/{applicationId}:
    get:
      tags:
        - Pricing
      summary: Get quotation for application
      description: Returns quotation details for a specific application
      operationId: getQuotation
      security:
        - BearerAuth: []
      parameters:
        - name: applicationId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Quotation retrieved
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/QuotationResponse'
        '401':
          description: Unauthorized
        '404':
          description: Application not found

  /api/v2/pricing/invoice/{phase}:
    get:
      tags:
        - Pricing
      summary: Get invoice for payment phase
      description: Returns invoice details for a specific payment phase
      operationId: getInvoice
      security:
        - BearerAuth: []
      parameters:
        - name: phase
          in: path
          required: true
          schema:
            type: string
            enum: [phase1, phase2]
      responses:
        '200':
          description: Invoice retrieved
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InvoiceResponse'
        '404':
          description: Phase not found

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    FeesResponse:
      type: object
      properties:
        success:
          type: boolean
        data:
          $ref: '#/components/schemas/PlatformFees'

    PlatformFees:
      type: object
      properties:
        applicationFee:
          type: number
          description: Application submission fee
          example: 5000
        inspectionFee:
          type: number
          description: Inspection and certification fee
          example: 25000
        renewalFee:
          type: number
          description: Certificate renewal fee
          example: 15000
        expediteFee:
          type: number
          description: Expedited processing fee
          example: 10000
        currency:
          type: string
          example: THB
        vatRate:
          type: number
          description: VAT rate (0 for government)
          example: 0
        lastUpdated:
          type: string
          format: date
        validUntil:
          type: string
          format: date

    QuotationResponse:
      type: object
      properties:
        success:
          type: boolean
        data:
          type: object
          properties:
            applicationId:
              type: string
            items:
              type: array
              items:
                $ref: '#/components/schemas/LineItem'
            subtotal:
              type: number
            vat:
              type: number
            total:
              type: number
            currency:
              type: string
            validDays:
              type: integer
            createdAt:
              type: string
              format: date-time

    InvoiceResponse:
      type: object
      properties:
        success:
          type: boolean
        data:
          type: object
          properties:
            phase:
              type: integer
              enum: [1, 2]
            description:
              type: string
            amount:
              type: number
            currency:
              type: string

    LineItem:
      type: object
      properties:
        description:
          type: string
        quantity:
          type: integer
        unitPrice:
          type: number
        total:
          type: number
