# GACP Strict Analysis Options
# Blueprint: "Code Quality & Standards"
# Rule: โค้ดต้องหน้าตาเหมือนกันทั้งทีม อ่านง่ายเหมือนคนเดียวเขียน

include: package:flutter_lints/flutter.yaml

analyzer:
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true
  errors:
    # Treat these as errors
    missing_required_param: error
    missing_return: error
    must_call_super: error
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "build/**"
    - ".dart_tool/**"

linter:
  rules:
    # Bloc/State Management
    close_sinks: true
    cancel_subscriptions: true
    
    # Error Prevention
    avoid_print: true
    avoid_empty_else: true
    no_duplicate_case_values: true
    prefer_void_to_null: true
    throw_in_finally: true
    
    # Null Safety
    avoid_null_checks_in_equality_operators: true
    use_if_null_to_convert_nulls_to_bools: true
    
    # Clean Code
    prefer_const_constructors: true
    prefer_const_declarations: true
    prefer_final_fields: true
    prefer_final_locals: true
    unnecessary_this: true
    unnecessary_const: true
    unnecessary_new: true
    
    # Documentation
    public_member_api_docs: false # Enable when mature
    
    # Style
    prefer_single_quotes: true
    always_declare_return_types: true
    avoid_unnecessary_containers: true

